spring.application.name=product-crud

# pastikan TIDAK ADA spasi atau teks lain di ujung baris ini
spring.datasource.url=jdbc:postgresql://ep-weathered-forest-ajmmh1j0-pooler.c-3.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YKX53bPmsTro
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect